# Generated by Django 6.0 on 2026-01-03 14:48

from django.db import migrations, models

import apps.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.files.models.file_upload_path,
                        validators=[
                            apps.files.models.validate_file_type,
                            apps.files.models.validate_file_size,
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Исходное имя файла"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("document", "Документ"),
                            ("archive", "Архив"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME тип"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Размер файла (в байтах)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный файл"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний доступ"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество скачиваний"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-upload_date"],
            },
        ),
    ]
