# Generated by Django 6.0 on 2026-01-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0002_remove_task_tasks_task_project_b78682_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.files.models.upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Оригинальное имя файла"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Документ"),
                            ("image", "Изображение"),
                            ("archive", "Архив"),
                            ("audio", "Аудио"),
                            ("video", "Видео"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME тип"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Размер файла (байты)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный доступ"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файловое вложение",
                "verbose_name_plural": "Файловые вложения",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["file_type"], name="files_filea_file_ty_59a4e1_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="files_filea_uploade_82f4bb_idx"
                    ),
                    models.Index(
                        fields=["task", "project", "user"],
                        name="files_filea_task_id_cea4ca_idx",
                    ),
                ],
            },
        ),
    ]
