# Generated by Django 6.0 on 2026-01-03 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загружено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь (для персональных файлов)",
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["upload_date"], name="files_filea_upload__cfe8bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["file_type"], name="files_filea_file_ty_59a4e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["is_public"], name="files_filea_is_publ_36b365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["uploaded_by"], name="files_filea_uploade_eb451c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["project"], name="files_filea_project_dc6abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(fields=["task"], name="files_filea_task_id_914f9e_idx"),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(fields=["user"], name="files_filea_user_id_e76556_idx"),
        ),
    ]
