FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    libmagic1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-django pytest-cov coverage

COPY . .

CMD ["python", "-m", "pytest", "--ds=backend.settings.testing", "--cov=apps", "--cov-report=term-missing"]
