# Generated by Django 6.0 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_department_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для уведомлений",
                max_length=50,
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
