# Generated by Django 6.0 on 2026-01-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата привязки Telegram"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Включить уведомления в Telegram",
                verbose_name="Telegram уведомления",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="@username в Telegram",
                max_length=100,
                null=True,
                verbose_name="Telegram Username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для уведомлений",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
