# Generated by Django 6.0 on 2025-12-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="task",
            name="tasks_task_project_b78682_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="tasks_task_assigne_7928f6_idx",
        ),
    ]
