# Generated by Django 6.0 on 2026-01-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="creator",
        ),
    ]
